apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: containerresourcenotexceed
spec:
  crd:
    spec:
      names:
        kind: ContainerResourceNotExceed
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            cpu:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package containerresourcenotexceed

        violation[{"msg": msg}] {
          general_violation[{"msg": msg, "field": "containers"}]
        }
        violation[{"msg": msg}] {
          general_violation[{"msg": msg, "field": "initContainers"}]
        }


        general_violation[{"msg": msg, "field": field}] {
          container := input.review.object.spec[field][_]
         
          requested_cpu := container.resources.requests[cpu]
          limited_cpu := input.parameters.cpu
          gap := requested - limited
          gap > 0
          msg := sprintf("container <%v> requested  <%v> cpus more than limited", [container.name, gap])
        }
